security_information/security_information/Controllers/AffineController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using security_information.Models;

namespace security_information.Controllers
{
    [RoutePrefix("affine")]
    public class AffineController : Controller
    {
        // GET: Affine
        public ActionResult Index()
        {
            return View();
        }

        [Route("encryption")]
        [HttpPost]
        public String Encript(String open_message = "", int a = 1, int shift = 1)
        {
            IEncryptor encryptor = new AffineEncryptor();
            return encryptor.encrypt(open_message, new object[] { a, shift });
        }

        [Route("decryption")]
        [HttpPost]
        public String Decript(String enc_message = "", int a = 1, int shift = 1)
        {
            IEncryptor encriptor = new AffineEncryptor();
            return encriptor.decrypt(enc_message, new object[] { a, shift });
        }
    }
}

security_information/security_information/Controllers/CaesarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using security_information.Models;

namespace security_information.Controllers
{
    [RoutePrefix("caesar")]
    public class CaesarController : Controller
    {
        // GET: Caesar
        public ActionResult Index()
        {
            return View();
        }

        [Route("encryption")]
        [HttpPost]
        public String Encript(String open_message = "", int shift = 1)
        {
            IEncryptor encryptor = new CaesarEncryptor();
            return encryptor.encrypt(open_message,new object[] { shift });
        }

        [Route("decryption")]
        [HttpPost]
        public String Decript(String enc_message = "", int shift = 1)
        {
            IEncryptor encriptor = new CaesarEncryptor();
            return encriptor.decrypt(enc_message, new object[] { shift});
        }
    }
}

security_information/security_information/Controllers/HillController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using security_information.Models;

namespace security_information.Controllers
{
    [RoutePrefix("hill")]
    public class HillController : Controller
    {
        // GET: Hill
        public ActionResult Index()
        {
            return View();
        }

        [Route("encryption")]
        [HttpPost]
        public String Encript(String open_message = "", int m = 1, String matrix = "")
        {

            IEncryptor encryptor = new HillEncryptor();
            return encryptor.encrypt(open_message, new object[] { m, matrix });
        }

        [Route("decryption")]
        [HttpPost]
        public String Decript(String enc_message = "", int m = 1, String matrix = "")
        {
            IEncryptor encriptor = new HillEncryptor();
            return encriptor.decrypt(enc_message, new object[] { m, matrix });
        }
    }
}

security_information/security_information/Controllers/SHA_1Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using security_information.Models.Hasher;

namespace security_information.Controllers
{
    [RoutePrefix("sha-1")]
    public class SHA_1Controller : Controller
    {
        // GET: SHA_1
        public ActionResult Index()
        {
            return View();
        }

        [Route("hash")]
        [HttpPost]
        public String hash(String input = "sha")
        {
            IHasher hasher = new SHA_1Hasher();
            return hasher.hash(input);
        }
    }
}

security_information/security_information/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <script src="~/scripts/jquery-2.2.0.min.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Информационная безопасность", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Шифр Цезаря", "Index", "Caesar")</li>
                    <li>@Html.ActionLink("Аффинный шифр", "Index", "Affine")</li>
                    <li>@Html.ActionLink("Шифр простой перестановки", "Index", "SimplePermutation")</li>
                    <li>@Html.ActionLink("Шифр Хилла", "Index", "Hill")</li>
                    <li>@Html.ActionLink("Асинхронный потоковый шифр", "Index", "SincStream")</li>
                    <li>@Html.ActionLink("DES-ECB", "Index", "DESECB")</li>
                    <li>@Html.ActionLink("AES", "Index", "AES")</li>
                    <li>@Html.ActionLink("SHA-1", "Index", "SHA_1")</li>
                    <li>@Html.ActionLink("ECDSA", "Index", "ECDSA")</li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>